// <auto-generated />
using System;
using FormProcessorApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FormProcessorApi.Migrations
{
    [DbContext(typeof(FormDetailsContext))]
    [Migration("20181021091518_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("FormProcessorApi.Models.Answer", b =>
                {
                    b.Property<string>("AnswerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PixelCount");

                    b.Property<int?>("QuestionId");

                    b.Property<int>("RegionBottomLeft");

                    b.Property<int>("RegionBottomRight");

                    b.Property<int>("RegionTopLeft");

                    b.Property<int>("RegionTopRight");

                    b.Property<bool>("Selected");

                    b.Property<string>("Text");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("FormProcessorApi.Models.FormDetails", b =>
                {
                    b.Property<int>("FormDetailsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Filename");

                    b.Property<bool>("IsTemplate");

                    b.Property<int>("TemplateId");

                    b.HasKey("FormDetailsId");

                    b.ToTable("FormDetails");
                });

            modelBuilder.Entity("FormProcessorApi.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FormDetailsId");

                    b.Property<int>("RegionBottomLeft");

                    b.Property<int>("RegionBottomRight");

                    b.Property<int>("RegionTopLeft");

                    b.Property<int>("RegionTopRight");

                    b.Property<string>("Text");

                    b.HasKey("QuestionId");

                    b.HasIndex("FormDetailsId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("FormProcessorApi.Models.Answer", b =>
                {
                    b.HasOne("FormProcessorApi.Models.Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId");
                });

            modelBuilder.Entity("FormProcessorApi.Models.Question", b =>
                {
                    b.HasOne("FormProcessorApi.Models.FormDetails")
                        .WithMany("Questions")
                        .HasForeignKey("FormDetailsId");
                });
#pragma warning restore 612, 618
        }
    }
}
